# Generated by Django 5.1.4 on 2024-12-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default=None, max_length=255)),
                ("ip", models.CharField(blank=True, max_length=255, null=True)),
                ("port", models.IntegerField(blank=True, default=6800, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("auth", models.IntegerField(blank=True, default=0, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
