# Generated by Django 5.1.4 on 2024-12-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_deploy_project_monitor_deploy_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='auth',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
